object Libs {
    const val APPCOMPAT = "androidx.appcompat:appcompat:${Versions.APPCOMPAT}"
    const val LIFECYCLE_EXTENSION = "androidx.lifecycle:lifecycle-extensions:${Versions.LIFECYCLE_VERSION}"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout:${Versions.CONSTRAINT_LAYOUT}"
    const val CORE_KTX = "androidx.core:core-ktx:${Versions.CORE_KTX}"
    const val MATERIAL = "com.google.android.material:material:${Versions.MATERIAL}"
    const val RX_KOTLIN = "io.reactivex.rxjava2:rxkotlin:${Versions.RX_KOTLIN}"
    const val RX_RELAY = "com.jakewharton.rxrelay2:rxrelay:${Versions.RX_RELAY}"
    const val RX_ANDROID = "io.reactivex.rxjava2:rxandroid:${Versions.RX_ANDROID}"
    const val ROOM_RUNTIME = "androidx.room:room-runtime:${Versions.ROOM}"
    const val ROOM_COMPILER = "androidx.room:room-compiler:${Versions.ROOM}"
    const val ROOM_RX = "androidx.room:room-rxjava2:${Versions.ROOM}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Versions.RETROFIT}"
    const val RETROFIT_RX_ADAPTER = "com.squareup.retrofit2:adapter-rxjava2:${Versions.RETROFIT}"
    const val RETROFIT_MOSHI_CONVERTER = "com.squareup.retrofit2:converter-moshi:${Versions.RETROFIT}"
    const val OK_HTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor:${Versions.OK_HTTP_LOGGING_INTERCEPTOR}"
    const val DAGGER_RUNTIME = "com.google.dagger:dagger:${Versions.DAGGER}"
    const val DAGGER_COMPILER = "com.google.dagger:dagger-compiler:${Versions.DAGGER}"
    const val NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment-ktx:${Versions.NAVIGATION}"
    const val NAVIGATION_UI = "androidx.navigation:navigation-ui-ktx:${Versions.NAVIGATION}"
    const val TIMBER = "com.jakewharton.timber:timber:${Versions.TIMBER}"
    const val THREE_TEN_ABP = "com.jakewharton.threetenabp:threetenabp:${Versions.THREE_TEN_ABP}"
    const val SWIPE_TO_REFRESH = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.SWIPE_TO_REFRESH}"

    object Testing {
        const val JUNIT = "junit:junit:${Versions.JUNIT}"
        const val ANDROID_X_CORE_TESTING = "androidx.test.ext:junit:${Versions.ANDROID_X_TEST}"
        const val ANDROID_X_TEST_RULES = "androidx.test:rules:${Versions.ANDROID_X_TEST}"
    }
}

private object Versions {
    const val KOTLIN = "1.4.21"
    const val APPCOMPAT = "1.2.0"
    const val CONSTRAINT_LAYOUT = "1.1.3"
    const val CORE_KTX = "1.3.2"
    const val MATERIAL = "1.2.1"
    const val JUNIT = "4.12"
    const val ANDROID_X_TEST = "1.1.2"
    const val RETROFIT = "2.7.0"
    const val OK_HTTP_LOGGING_INTERCEPTOR = "4.0.1"
    const val ROOM = "2.2.3"
    const val DAGGER = "2.31"
    const val RX_KOTLIN = "2.4.0"
    const val RX_RELAY = "2.1.1"
    const val RX_ANDROID = "2.1.1"
    const val LIFECYCLE_VERSION = "2.1.0"
    const val NAVIGATION = "2.1.0"
    const val TIMBER = "4.7.1"
    const val THREE_TEN_ABP = "1.2.2"
    const val SWIPE_TO_REFRESH = "1.0.0"
}
